change BrowserModule , BrowserAnimationsModule --> CommonModule
    imports: [BrowserModule , BrowserAnimationsModule]  --> Works only if library is used in Master Module.. Throws error when used in Secondary Modules during loading /*  imports: [BrowserModule , BrowserAnimationsModule]  --> getting error
  Error: BrowserModule has already been loaded. If you need access to common directives  such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.*/